const ALERT = "ALERT";

const REFETCH_CHATS = "REFETCH_CHATS";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_REQUEST = "NEW_REQUEST";

const NEW_MESSAGES_ALERT = "NEW_MESSAGES_ALERT";

const NEW_MESSAGE = "NEW_MESSAGE";

const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

const CHAT_JOINED = "CHAT_JOINED";
const CHAT_LEAVED = "CHAT_LEAVED";

const  ONLINE_USERS =  "ONLINE_USERS"

export {
  ALERT,
  REFETCH_CHATS,
  NEW_ATTACHMENT,
  NEW_MESSAGES_ALERT,
  NEW_REQUEST,
  NEW_MESSAGE,
  STOP_TYPING,
  START_TYPING,
  CHAT_JOINED,
  CHAT_LEAVED,
  ONLINE_USERS
};
